apiVersion: v1
kind: Service
metadata:
    name: main-manifold
spec:
    selector:
        app: oil-flow
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
    type: NodePort
